### ISSUE TITLE
Set up TypeScript

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes-electron#6]
We have our application in js and have to move on to using TypeScript

**Comment by DavidCabal** [comment]
I'll knock this out.

**Comment by aquibbaig** [comment]
@DavidCabal Sure! Good luck.

**Comment by HarisSpahija** [comment]
Hey @DavidCabal , maybe its an idea to add a tslint config? I can pick this up if you want!

**Comment by ganeshpatro321** [comment]
Hey @HarisSpahija I think they are planning to deprecate the tslint, and we have already configured the eslint which supports the typescript thing.

**Comment by ankitjena** [comment]
I think we can close this
